# Generated by Django 3.1.3 on 2020-11-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_followed', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='users_followed',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_followed_by', to='users_followed.UsersFollowed'),
        ),
    ]
