# Generated by Django 3.1.3 on 2020-11-25 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_number',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='likes.likes'),
            preserve_default=False,
        ),
    ]
