# Generated by Django 3.1.3 on 2020-11-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_number', models.IntegerField(blank=True, default=0, null=True)),
                ('list_of_users_that_like_it', models.ManyToManyField(blank=True, to='user.User')),
            ],
        ),
    ]
