export const LOG_IN_USER_SUCCESS = "LOG_IN_USER_SUCCESS";
export const LOG_OUT_USER_SUCCESS = "LOG_OUT_USER_SUCCESS";
export const COOKIES_ACCEPTED = "COOKIES_ACCEPTED";
export const SET_ARRAY_OF_POSTS_TO_DISPLAY = "SET_ARRAY_OF_POSTS_TO_DISPLAY";
export const SET_ARRAY_OF_USERNAMES_OF_FOLLOWED_USERS = "SET_ARRAY_OF_USERNAMES_OF_FOLLOWED_USERS";
